name: esplink-mvw

on:
 # push:
 #   branches: [ master ]
  #pull_request:
  #  branches: [ master ]
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '9'
        distribution: 'adopt'
    - name: 1:install net-tools
      run: sudo apt-get install net-tools
    - name: 2:Installation des dépendances
      run: sudo apt-get install make unrar-free autoconf automake libtool gcc g++ gperf flex bison texinfo gawk ncurses-dev libexpat-dev python-dev python sed git unzip bash help2man wget bzip2
    - name: 3:install other tools
      run: sudo apt-get install libtool-bin curl zlib1g-dev  python-serial 
      
    - name: ls
      run: ls /
    - name: ls
      run: ls /home
    #- name: 4:Installation d’Open-SDK
    #  run: sudo apt-get install  python-serial openjdk-9-jre
    - name: 4:Installation d’Open-SDK
      run: git clone --recursive https://github.com/pfalcon/esp-open-sdk.git
    - name: ls
      run: ls /home/runner/work/esp-link-mvw/esp-link-mvw/
    - name: cd
      run: cd /home/runner/work/esp-link-mvw/esp-link-mvw/esp-open-sdk
    - name: make
      run: make STANDALONE=n
    - name: export PATH
      run: export PATH=/home/runner/work/esp-link-mvw/esp-open-sdk/xtensa-lx106-elf/bin:$PATH
    - name: Download sources d’ESP-LINK
      run: wget https://caron.ws/wp-content/uploads/telechargement/esp-link-3.2.47.alpha.zip
           unzip esp-link-3.2.47.alpha.zip
           cd esp-link-3.2.47.alpha
           sudo curl -Ls http://s3.voneicken.com/xtensa-lx106-elf-20160330.tgx | tar Jxf –
           sudo curl -Ls http://s3.voneicken.com/esp_iot_sdk_v2.1.0.tgx | tar -C .. -Jxf –
           export XTENSA_TOOLS_ROOT=$PWD/xtensa-lx106-elf/bin/
           make
    #- name: Build Conversations (System)
    #  run: ./gradlew assembleConversationsFreeSystemDebug
    - uses: actions/upload-artifact@v2
      with:
        name: esp-link-3.2.47.alpha-firmware
        #path: ./build/outputs/apk/**/debug/Conversations-2.10.2-conversations-free-system-universal-debug.apk
        path: /home/chris/esp-link-3.2.47.alpha/firmware
